swiety85/angular2gridster

README.md
demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.service.ts
demo/src/polyfills.ts
src/gridster-item/gridster-item.component.ts
src/gridster.component.ts
src/gridster.service.ts

- dragging item fix
- add missing System.js doc
- add polyfills for demo page to support older IE

Dragging fix

---

demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/gridster/gridster.component.ts
src/gridster.component.ts

- provide possibility to change `widthHeightRatio ` option
- update demo with input to change `widthHeightRatio` option

Dynamic widthHeightRatio option change

---

demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/gridster/gridList/GridListItem.ts
demo/src/app/gridster/gridList/gridList.ts
demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster-prototype/gridster-item-prototype.directive.ts
demo/src/app/gridster/gridster.service.ts
src/gridList/GridListItem.ts
src/gridList/gridList.ts
src/gridster-item/gridster-item.component.ts
src/gridster-prototype/gridster-item-prototype.directive.ts
src/gridster.service.ts

- enable/disable dragging for single item
- enable/disable resizing for single item

#22 Allow fixed elements in grid 

---

demo/src/app/app.component.css
demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/gridster/GridsterOptions.ts
demo/src/app/gridster/IGridsterOptions.ts
demo/src/app/gridster/gridList/GridListItem.ts
demo/src/app/gridster/gridList/gridList.ts
demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster-prototype/gridster-prototype.service.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.service.ts
src/GridsterOptions.ts
src/IGridsterOptions.ts
src/gridList/GridListItem.ts
src/gridList/gridList.ts
src/gridster-item/gridster-item.component.ts
src/gridster-prototype/gridster-prototype.service.ts
src/gridster.component.ts
src/gridster.service.ts
src/index.ts

Implement responsive behaviour for girdster by:
* possible to configure 5 different breakpoints
* different gridster configuration for different breakpoints
* automatically adjusting items position and size to breakpoint configuration
* easy way to connect items positions to any place outside of component

19 mobile view

---

README.md
demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/app.module.ts
demo/src/app/gridster/GridsterOptions.ts
demo/src/app/gridster/IGridsterOptions.ts
demo/src/app/gridster/gridList/GridListItem.ts
demo/src/app/gridster/gridList/gridList.ts
demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster-prototype/gridster-prototype.service.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.service.ts
demo/src/app/test/test.component.html
demo/src/app/test/test.component.ts
src/GridsterOptions.ts
src/IGridsterOptions.ts
src/gridList/GridListItem.ts
src/gridList/gridList.ts
src/gridster-item/gridster-item.component.ts
src/gridster-prototype/gridster-prototype.service.ts
src/gridster.component.ts
src/gridster.service.ts

- new event (change) on GridsterItem component
- improve process of Gridster init
- update demo
- update readme.md

Gridster item options #30

---

package.json

Try to fix bug with angular-cli #57

Reorganise project deps

---

demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.service.ts
src/gridster.component.ts
src/gridster.service.ts

Update gridster element item on drag start

---

demo/src/app/gridster/gridster-item/gridster-item.component.ts
src/gridster-item/gridster-item.component.ts

Fix for: ResponsiveView & responsiveOptions defaults causing snap
issues with new items #74

Fix snap issue with new items and no responsive configuration

---

demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.service.ts
src/gridster-item/gridster-item.component.ts
src/gridster.component.ts
src/gridster.service.ts

Make dragging works when gridster is in scrollable element. Issue #21

Make dragging works when gridster is in scrollable element

---

demo/src/app/gridster/utils/draggable.ts
src/utils/draggable.ts

Drag & Drop doesn't work in Edge on touch device (tablet / mobile) #72

Fix problem with IE touch drag by touch-action css

---

demo/src/app/gridster/gridster.service.ts
src/gridster.service.ts

- Fix problem with setting width on gridster element #85

Fix problem with setting gridster width

---

src/gridList/gridList.ts
src/gridster-prototype/gridster-prototype.service.ts

- Illustates -> Illustrates
- a an item  -> an item
- marge the brached-out -> merge the branched-out
- wheter -> whether

fix: typos

---

demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.service.ts
src/gridster.component.ts
src/gridster.service.ts

Add events when reflowing grid items

---

demo/src/app/gridster/gridList/gridList.ts
demo/src/app/gridster/utils/draggable.ts
src/utils/draggable.ts

Fix problem with focused el when dragging in IE

---

demo/src/app/app.component.css
demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/utils/utils.ts
demo/src/styles.css
src/gridList/gridList.ts
src/gridster.component.ts
src/utils/utils.ts

Auto height for item

---

demo/src/app/app.component.css
demo/src/app/app.component.html
demo/src/app/gridster/IGridsterDraggableOptions.ts
demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster.service.ts
demo/src/app/gridster/utils/draggable.ts
demo/src/app/gridster/utils/utils.ts
demo/src/styles.css
src/IGridsterDraggableOptions.ts
src/gridList/gridList.ts
src/gridster-item/gridster-item.component.ts
src/gridster.service.ts
src/utils/draggable.ts
src/utils/utils.ts

Scroll container while dragging

---

demo/package.json
demo/src/app/app.component.css
package.json

Add command to update demo

---

.gitignore
README.md
demo/package.json
demo/src/app/gridster/GridsterOptions.ts
demo/src/app/gridster/IGridsterDraggableOptions.ts
demo/src/app/gridster/IGridsterOptions.ts
demo/src/app/gridster/gridList/GridListItem.ts
demo/src/app/gridster/gridList/gridList.ts
demo/src/app/gridster/gridster-item/gridster-item.component.ts
demo/src/app/gridster/gridster-prototype/gridster-item-prototype.directive.ts
demo/src/app/gridster/gridster-prototype/gridster-prototype.service.ts
demo/src/app/gridster/gridster.component.ts
demo/src/app/gridster/gridster.module.ts
demo/src/app/gridster/gridster.service.ts
demo/src/app/gridster/utils/DraggableEvent.ts
demo/src/app/gridster/utils/draggable.ts
demo/src/app/gridster/utils/utils.ts
package.json

Reverts swiety85/angular2gridster#145

Revert "fix: remove directory demo/src/app/gridster/, add symlink"

---

src/gridster-item/gridster-item.component.ts
src/utils/draggable.ts

feat(scroll): restrict scroll direction to gridster direction

---

demo/src/app/app.component.html
demo/src/app/app.component.ts
src/gridList/gridList.ts
src/gridster-item/gridster-item.component.ts
src/utils/DraggableEvent.ts
src/utils/draggable.ts

158 resize binding fix

---

demo/src/app/app.component.ts
src/IGridsterOptions.ts
src/gridster.service.ts

feat: display grid lines on drag and resize

---

src/gridster.service.ts

fix: error when lazy loading widgets

---

src/gridster-item/gridster-item.component.ts
src/gridster.component.ts

fix(config): correct applying dragAndDrop and resizable options on init

---

src/gridster.component.ts

Also use `subscription.add` instead of an array of subscription. I don't know how you feel about this. (I personally prefer `takeUntil`)

fix(gridster): add missing unsubscribe

---

README.md
src/gridster.service.ts

Define _items initially

---

package.json
src/gridster.service.ts

fix(drag): Prevent moving item to negative position

---

package-lock.json
src/gridList/gridList.ts

The problem happened because items width bigger than gridster lanes did
not allow dropping item.
Fixes #183

fix(drag): Solve problem with dropping items in single lane

---

src/gridList/gridList.ts

fix(drag): Fix overlapping in different breakpoints after item resize with floating on false

---

src/gridster.service.ts

fix: Hide grid lines on item drag out

---

src/gridList/gridList.ts
src/gridster.service.ts

fix(drag): Fix problem with resolving collision with gridster gravity on false

---

src/gridster.service.ts

fix(drag): Prevent gravity of dragged element on drop

---

demo/src/app/app.component.css
demo/src/app/app.component.html
demo/src/app/app.component.ts
src/gridster-item/gridster-item.component.ts
src/gridster-prototype/gridster-prototype.service.ts
src/gridster.component.ts
src/gridster.service.ts

123 Gridster inside gridster

---

demo/package.json
demo/src/app/app.component.css
src/gridster-item/gridster-item.component.ts
src/gridster.service.ts

229 Gridster widget config model changes onDestroy due to two way binding on positions

---

src/gridster-prototype/gridster-prototype.service.ts

fix(drag): Fix error on prototype drag start

---

src/IGridsterOptions.ts
src/gridster.service.ts

feat(config): Add option lines.always to always show grid lines

---

src/gridList/gridList.ts
src/gridster.service.ts

fix(drag): Remove restriction about dragging items down/right

---

src/gridList/gridList.ts
src/gridster.service.ts

feat(api): extend "change" event object to have isNew and oldValues

---

src/gridster-item/gridster-item.component.ts

fix: Remove error when adding new widgets with no responsiveOptions

---

src/utils/DraggableEvent.ts
src/utils/draggable.ts

fix: Make click event to be triggered on touch in drag handler

---

README.md
demo/src/app/app.module.ts
src/gridster.module.ts

feat: allow drag prototypes to different gridsters in different modules

---

projects/angular2gridster/src/lib/gridster-item/gridster-item.component.ts
projects/angular2gridster/src/lib/gridster.service.ts

Optimize amount of render calls

fix: position and size binding on outside change

---

projects/angular2gridster/src/lib/gridList/gridList.ts

Fix: change event - oldValues empty when value = 0

---

projects/angular2gridster/src/lib/gridster.component.ts

fix: set default draggableOptions to empty object

---

package.json
src/gridList/GridListItem.ts
src/gridster.module.ts
src/index.ts
src/utils/draggable.ts
tsconfig-lib.json

295 productive build still fails

---

projects/angular2gridster/src/public_api.ts

fix: Expose private exports in bundle

---

projects/angular2gridster/src/lib/utils/draggable.ts

fix: fix element.style is undefined error

---

projects/angular2gridster/src/lib/gridster.component.ts
projects/angular2gridster/src/lib/utils/utils.ts
src/app/app.component.css

Gridster in scrollable container

---

projects/angular2gridster/src/lib/GridsterOptions.ts
projects/angular2gridster/src/lib/IGridsterOptions.ts
projects/angular2gridster/src/lib/gridster.component.ts
src/app/app.component.html
src/app/app.component.ts

Responsiveness base on container width
